# Generated by Django 4.2.16 on 2024-09-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EudamedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('manufacturer_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FdaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('manufacturer_name', models.CharField(max_length=255)),
            ],
        ),
    ]
